window.GPU_TCO_STARFLEET_CONFIG = Object.freeze({
  enabled: false,
  providerName: "Starfleet",
  serviceId: "SweHG9LrCP4FbckLjhJFxRNrsSKCQKch3z0fDUINxnA",
  nspectId: "NSPECT-5LTJ-V6DK",
  authBaseUrl: "",
  apiBaseUrl: "",
  clientId: "StkDvtzs9LkXP6-N6yhVmfi_vEd_m3zErlk5g-OOdqY",
  redirectUri: "",
  requiredEmailDomain: "nvidia.com",
  inviteOnlyExternalUsers: true,
  adminEmails: ["deanh@nvidia.com"],
  adminGroup: "",
  savedConfigurationsResource: "gpu-tco-configurations",
  activityLogResource: "gpu-tco-activity",
});
